approvedGitRepositories:
  - '**'

enableScripts: true

nodeLinker: node-modules

npmScopes:
  awesome:
    npmAlwaysAuth: true
    npmAuthToken: ECB95473-FBAF-463F-905C-C9ED4C00D519
    npmRegistryServer: 'https://npm.fontawesome.com/'
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: ECB95473-FBAF-463F-905C-C9ED4C00D519
    npmRegistryServer: 'https://npm.fontawesome.com/'
